- name: Invite users
  hosts: controller
  gather_facts: false
  collections:
    - f5devcentral.cloudservices
  connection: httpapi

  vars:
    ansible_network_os: f5devcentral.cloudservices.f5
    ansible_host: "api.cloudservices.f5.com"
    ansible_user: "{{ lookup('env','F5_USERNAME') }}"
    ansible_httpapi_password: "{{ lookup('env','F5_PASSWORD') }}"
    ansible_httpapi_use_ssl: yes
    users_csv: "users.csv"

  tasks:
    - name: "Read user information"
      read_csv:
        path: "{{ users_csv }}"
      register: users

    - name: "Get an organization"
      f5_cs_organization:
        state: "fetch"
        name: "{{ user.organization }}"
      register: organizations
      loop: "{{ users.list }}"
      loop_control:
        loop_var: user

    - name: "Invite user"
      f5_cs_users:
        account_id: "{{ org.account_id }}"
        state: "present"
        users:
          - email: "{{ org.user.email | lower }}"
            first_name: "{{ org.user.first_name }}"
            last_name: "{{ org.user.last_name }}"
            role_name: "limited-user"
      loop: "{{ organizations.results }}"
      loop_control:
        loop_var: org
